### ISSUE TITLE
Header image option not interpreted correctly on initial site creation

### ISSUE THREAD

**Issue by marpa** [clas-web/variations-template-theme#18]
When a new site is created from the New Blog Template plugin, the default header is not appearing, even though it is specified in the theme options.

**Comment by marpa** [comment]
Here's a site that was created with the blog template, see:
https://clas-incubator-wp.uncc.edu/test00004
blogid=913

In the customizer, a header image is selected, but is it not appearing in the preview.

**Comment by atrus1701** [comment]
This is due to the url to path function needed to get the header image size.  It was not designed to work with url that lead to other sites.  I have modified the function to use the url when determining the image size, which will only work if the PHP on the production server has the correct option enabled, which it does.
6e54b094c163288097b373bcc3a5b48868adffe6
